package scaffold.forms;

import scaffold.uml.basic.cm.CmAssociation;
import scaffold.uml.basic.cm.CmAssocEnd;
import javax.swing.JFrame;


public class UMLAssociationForm extends javax.swing.JFrame {
    public UMLAssociationForm(CmAssociation relationship) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.relationship = relationship;
    }

    public void loadValues() {
        CmAssocEnd ep1 = relationship.getEndPoint1();
        
        if (ep1.getName()!= null) {
            roleName1.setText(ep1.getName());
        }
        
        if (ep1.getMultiplicity() != null) {
            multiplicity1.setText(ep1.getMultiplicity().getExpression());
        }       
        
        CmAssocEnd ep2 = relationship.getEndPoint2();
        
        if (ep2.getName() != null) {
            roleName2.setText(ep2.getName());
        }
        
        if (ep2.getMultiplicity() != null) {
            multiplicity2.setText(ep2.getMultiplicity().getExpression());
        }        
                
        role1VisibleCheckbox.setSelected(ep1.isNavigable());
        role2VisibleCheckbox.setSelected(ep2.isNavigable());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        GeneralPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        generalOkButton = new javax.swing.JButton();
        generalCancelButton = new javax.swing.JButton();
        Role1Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roleName1 = new javax.swing.JTextField();
        multiplicity1 = new javax.swing.JTextField();
        role1OK = new javax.swing.JButton();
        role1Cancel = new javax.swing.JButton();
        role1VisibleCheckbox = new javax.swing.JCheckBox();
        Role2Panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roleName2 = new javax.swing.JTextField();
        multiplicity2 = new javax.swing.JTextField();
        role2OK = new javax.swing.JButton();
        role2Cancel = new javax.swing.JButton();
        role2VisibleCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setText("Description");

        generalOkButton.setText("OK");
        generalOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalOkButtonActionPerformed(evt);
            }
        });

        generalCancelButton.setText("Cancel");
        generalCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GeneralPanelLayout = new javax.swing.GroupLayout(GeneralPanel);
        GeneralPanel.setLayout(GeneralPanelLayout);
        GeneralPanelLayout.setHorizontalGroup(
            GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPanelLayout.createSequentialGroup()
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(generalOkButton)
                        .addGap(139, 139, 139)
                        .addComponent(generalCancelButton))
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        GeneralPanelLayout.setVerticalGroup(
            GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generalOkButton)
                    .addComponent(generalCancelButton))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", GeneralPanel);

        jLabel2.setText("Role Name");

        jLabel3.setText("Multiplicity");

        role1OK.setText("OK");
        role1OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role1OKActionPerformed(evt);
            }
        });

        role1Cancel.setText("Cancel");
        role1Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role1CancelActionPerformed(evt);
            }
        });

        role1VisibleCheckbox.setText("navigable");

        javax.swing.GroupLayout Role1PanelLayout = new javax.swing.GroupLayout(Role1Panel);
        Role1Panel.setLayout(Role1PanelLayout);
        Role1PanelLayout.setHorizontalGroup(
            Role1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Role1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Role1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Role1PanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roleName1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Role1PanelLayout.createSequentialGroup()
                        .addGroup(Role1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Role1PanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(multiplicity1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Role1PanelLayout.createSequentialGroup()
                                .addComponent(role1OK)
                                .addGap(129, 129, 129)))
                        .addGap(12, 12, 12)
                        .addComponent(role1Cancel))
                    .addComponent(role1VisibleCheckbox))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Role1PanelLayout.setVerticalGroup(
            Role1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Role1PanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(Role1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(roleName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Role1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(multiplicity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(role1VisibleCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(Role1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(role1OK)
                    .addComponent(role1Cancel))
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Role 1", Role1Panel);

        jLabel4.setText("Role Name");

        jLabel5.setText("Multiplicity");

        roleName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleName2ActionPerformed(evt);
            }
        });

        role2OK.setText("OK");
        role2OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role2OKActionPerformed(evt);
            }
        });

        role2Cancel.setText("Cancel");
        role2Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role2CancelActionPerformed(evt);
            }
        });

        role2VisibleCheckbox.setText("navigable");

        javax.swing.GroupLayout Role2PanelLayout = new javax.swing.GroupLayout(Role2Panel);
        Role2Panel.setLayout(Role2PanelLayout);
        Role2PanelLayout.setHorizontalGroup(
            Role2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Role2PanelLayout.createSequentialGroup()
                .addGroup(Role2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Role2PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Role2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Role2PanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(multiplicity2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Role2PanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(roleName2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(role2VisibleCheckbox)))
                    .addGroup(Role2PanelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(role2OK)
                        .addGap(136, 136, 136)
                        .addComponent(role2Cancel)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        Role2PanelLayout.setVerticalGroup(
            Role2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Role2PanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Role2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(roleName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Role2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(multiplicity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(role2VisibleCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(Role2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(role2OK)
                    .addComponent(role2Cancel))
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Role 2", Role2Panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roleName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleName2ActionPerformed

    private void role2OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role2OKActionPerformed
        handleOK();
    }//GEN-LAST:event_role2OKActionPerformed

    private void generalOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalOkButtonActionPerformed
        handleOK();
    }//GEN-LAST:event_generalOkButtonActionPerformed

    private void generalCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_generalCancelButtonActionPerformed

    private void role1OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role1OKActionPerformed
        handleOK();
    }//GEN-LAST:event_role1OKActionPerformed

    private void role1CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role1CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_role1CancelActionPerformed

    private void role2CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role2CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_role2CancelActionPerformed

    private void handleOK() {
        CmAssocEnd ep1 = relationship.getEndPoint1();
        
        if (ep1.getName() == null || !ep1.getName().equals(roleName1.getText())) {
            ep1.setName(roleName1.getText());
        }
        
        if (ep1.getMultiplicity() == null || !ep1.getMultiplicity().getExpression().equals(multiplicity1.getText())) {
            ep1.getMultiplicity().setExpression(multiplicity1.getText());
        }       
        
        CmAssocEnd ep2 = relationship.getEndPoint2();
        
        if (ep2.getName() == null || !ep2.getName().equals(roleName2.getText())) {
            ep2.setName(roleName2.getText());
        }
        
        if (ep2.getMultiplicity() == null || !ep2.getMultiplicity().getExpression().equals(multiplicity2.getText())) {
            ep2.getMultiplicity().setExpression(multiplicity2.getText());
        }
        
        if (ep1.isNavigable() != role1VisibleCheckbox.isSelected()) {
            ep1.setNavigable(role1VisibleCheckbox.isSelected());
        }
        if (ep2.isNavigable() != role2VisibleCheckbox.isSelected()) {
            ep2.setNavigable(role2VisibleCheckbox.isSelected());
        }
        
        this.dispose();
    }
    
    private CmAssociation relationship;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GeneralPanel;
    private javax.swing.JPanel Role1Panel;
    private javax.swing.JPanel Role2Panel;
    private javax.swing.JButton generalCancelButton;
    private javax.swing.JButton generalOkButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField multiplicity1;
    private javax.swing.JTextField multiplicity2;
    private javax.swing.JButton role1Cancel;
    private javax.swing.JButton role1OK;
    private javax.swing.JCheckBox role1VisibleCheckbox;
    private javax.swing.JButton role2Cancel;
    private javax.swing.JButton role2OK;
    private javax.swing.JCheckBox role2VisibleCheckbox;
    private javax.swing.JTextField roleName1;
    private javax.swing.JTextField roleName2;
    // End of variables declaration//GEN-END:variables
}
