package scaffold.forms;

import scaffold.uml.basic.cm.CmAssociation;
import scaffold.uml.basic.cm.CmAssocEnd;
import scaffold.graphics.graph.uml.UMLEndPoint;
import scaffold.graphics.graph.uml.UMLAggregationLink;
import javax.swing.JFrame;


public class UMLAggregationForm extends javax.swing.JFrame {
    public UMLAggregationForm(UMLAggregationLink link, CmAssociation assoc) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.link = link;
        this.assoc = assoc;
    }

    public void loadValues() {     
        compositeCheckBox.setSelected(assoc.isComposite());        
      
        CmAssocEnd containerEP = (link.getEndPoint1().getEPType() == UMLEndPoint.EPType.AGGREGATE)
                ? assoc.getEndPoint1() : assoc.getEndPoint2();        
        
        if (containerEP.getName() != null ) {
            containerRoleName.setText(containerEP.getName());
        }        
        
        if (containerEP.getMultiplicity() != null) {
            containerMultiplicity.setText(containerEP.getMultiplicity().getExpression());
        }                      
        
        CmAssocEnd containeeEP = (link.getEndPoint1().getEPType() != UMLEndPoint.EPType.AGGREGATE)
                ? assoc.getEndPoint1() : assoc.getEndPoint2();
        
        if (containeeEP.getName() != null ) {
            containeeRoleName.setText(containeeEP.getName());
        }        
        
        if (containeeEP.getMultiplicity() != null) {
            containeeMultiplicity.setText(containeeEP.getMultiplicity().getExpression());
        }             
        
        containerVisibleCheckbox.setSelected(containerEP.isNavigable());
        containeeVisibleCheckbox.setSelected(containeeEP.isNavigable());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        GeneralPanel = new javax.swing.JPanel();
        compositeCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        generalOkButton = new javax.swing.JButton();
        generalCancelButton = new javax.swing.JButton();
        ContainerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        containerRoleName = new javax.swing.JTextField();
        containerMultiplicity = new javax.swing.JTextField();
        containerOK = new javax.swing.JButton();
        containerCancel = new javax.swing.JButton();
        containerVisibleCheckbox = new javax.swing.JCheckBox();
        ContaineePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        containeeRoleName = new javax.swing.JTextField();
        containeeMultiplicity = new javax.swing.JTextField();
        containeeOK = new javax.swing.JButton();
        containeeCancel = new javax.swing.JButton();
        containeeVisibleCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        compositeCheckBox.setText("Composition");

        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setText("Description");

        generalOkButton.setText("OK");
        generalOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalOkButtonActionPerformed(evt);
            }
        });

        generalCancelButton.setText("Cancel");
        generalCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GeneralPanelLayout = new javax.swing.GroupLayout(GeneralPanel);
        GeneralPanel.setLayout(GeneralPanelLayout);
        GeneralPanelLayout.setHorizontalGroup(
            GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPanelLayout.createSequentialGroup()
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(compositeCheckBox))
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(generalOkButton)
                        .addGap(139, 139, 139)
                        .addComponent(generalCancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GeneralPanelLayout.setVerticalGroup(
            GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(compositeCheckBox)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generalOkButton)
                    .addComponent(generalCancelButton))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", GeneralPanel);

        jLabel2.setText("Role Name");

        jLabel3.setText("Multiplicity");

        containerMultiplicity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                containerMultiplicityActionPerformed(evt);
            }
        });

        containerOK.setText("OK");
        containerOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                containerOKActionPerformed(evt);
            }
        });

        containerCancel.setText("Cancel");
        containerCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                containerCancelActionPerformed(evt);
            }
        });

        containerVisibleCheckbox.setText("isNavigable");

        javax.swing.GroupLayout ContainerPanelLayout = new javax.swing.GroupLayout(ContainerPanel);
        ContainerPanel.setLayout(ContainerPanelLayout);
        ContainerPanelLayout.setHorizontalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(containerRoleName))
                    .addGroup(ContainerPanelLayout.createSequentialGroup()
                        .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(containerVisibleCheckbox)
                            .addGroup(ContainerPanelLayout.createSequentialGroup()
                                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ContainerPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(containerMultiplicity, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerPanelLayout.createSequentialGroup()
                                        .addComponent(containerOK)
                                        .addGap(141, 141, 141)))
                                .addComponent(containerCancel)))
                        .addGap(0, 173, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContainerPanelLayout.setVerticalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(containerRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(containerMultiplicity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(containerVisibleCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(containerOK)
                    .addComponent(containerCancel))
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Container", ContainerPanel);

        jLabel4.setText("Role Name");

        jLabel5.setText("Multiplicity");

        containeeRoleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                containeeRoleNameActionPerformed(evt);
            }
        });

        containeeOK.setText("OK");
        containeeOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                containeeOKActionPerformed(evt);
            }
        });

        containeeCancel.setText("Cancel");
        containeeCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                containeeCancelActionPerformed(evt);
            }
        });

        containeeVisibleCheckbox.setText("isNavigable");
        containeeVisibleCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                containeeVisibleCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContaineePanelLayout = new javax.swing.GroupLayout(ContaineePanel);
        ContaineePanel.setLayout(ContaineePanelLayout);
        ContaineePanelLayout.setHorizontalGroup(
            ContaineePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContaineePanelLayout.createSequentialGroup()
                .addGroup(ContaineePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContaineePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ContaineePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContaineePanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(containeeRoleName))
                            .addGroup(ContaineePanelLayout.createSequentialGroup()
                                .addGroup(ContaineePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(containeeVisibleCheckbox)
                                    .addGroup(ContaineePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(containeeMultiplicity, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 241, Short.MAX_VALUE))))
                    .addGroup(ContaineePanelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(containeeOK)
                        .addGap(136, 136, 136)
                        .addComponent(containeeCancel)))
                .addContainerGap())
        );
        ContaineePanelLayout.setVerticalGroup(
            ContaineePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContaineePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(ContaineePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(containeeRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ContaineePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(containeeMultiplicity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(containeeVisibleCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(ContaineePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(containeeOK)
                    .addComponent(containeeCancel))
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Containee", ContaineePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void containeeRoleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_containeeRoleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_containeeRoleNameActionPerformed

    private void containeeOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_containeeOKActionPerformed
        handleOK();
    }//GEN-LAST:event_containeeOKActionPerformed

    private void generalOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalOkButtonActionPerformed
        handleOK();
    }//GEN-LAST:event_generalOkButtonActionPerformed

    private void generalCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_generalCancelButtonActionPerformed

    private void containerOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_containerOKActionPerformed
        handleOK();
    }//GEN-LAST:event_containerOKActionPerformed

    private void containerCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_containerCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_containerCancelActionPerformed

    private void containeeCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_containeeCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_containeeCancelActionPerformed

    private void containeeVisibleCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_containeeVisibleCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_containeeVisibleCheckboxActionPerformed

    private void containerMultiplicityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_containerMultiplicityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_containerMultiplicityActionPerformed

    private void handleOK() {
        if (compositeCheckBox.isSelected() != assoc.isComposite()) {            
            assoc.setComposite(compositeCheckBox.isSelected());
        }        
        
        CmAssocEnd containerEP = (link.getEndPoint1().getEPType() == UMLEndPoint.EPType.AGGREGATE)
                ? assoc.getEndPoint1() : assoc.getEndPoint2();        
        
        if (containerEP.getName() == null || !containerEP.getName().equals(containerRoleName.getText())) {
            containerEP.setName(containerRoleName.getText());
        }
        
        if (containerEP.getMultiplicity() == null || !containerEP.getMultiplicity().getExpression().equals(containerMultiplicity.getText())) {
            containerEP.getMultiplicity().setExpression(containerMultiplicity.getText());
        }                           
        
        CmAssocEnd containeeEP = (link.getEndPoint1().getEPType() != UMLEndPoint.EPType.AGGREGATE)
                ? assoc.getEndPoint1() : assoc.getEndPoint2();
        
        if (containeeEP.getName() == null || !containeeEP.getName().equals(containeeRoleName.getText())) {
            containeeEP.setName(containeeRoleName.getText());
        }
        
        if (containeeEP.getMultiplicity() == null || !containeeEP.getMultiplicity().getExpression().equals(containeeMultiplicity.getText())) {
            containeeEP.getMultiplicity().setExpression(containeeMultiplicity.getText());
        }       
        
        if (containerEP.isNavigable() != containerVisibleCheckbox.isSelected()) {
            containerEP.setNavigable(containerVisibleCheckbox.isSelected());
        }
        if (containeeEP.isNavigable() != containeeVisibleCheckbox.isSelected()) {
            containeeEP.setNavigable(containeeVisibleCheckbox.isSelected());
        }
        
        this.dispose();
    }
    
    private UMLAggregationLink link;
    private CmAssociation assoc;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContaineePanel;
    private javax.swing.JPanel ContainerPanel;
    private javax.swing.JPanel GeneralPanel;
    private javax.swing.JCheckBox compositeCheckBox;
    private javax.swing.JButton containeeCancel;
    private javax.swing.JTextField containeeMultiplicity;
    private javax.swing.JButton containeeOK;
    private javax.swing.JTextField containeeRoleName;
    private javax.swing.JCheckBox containeeVisibleCheckbox;
    private javax.swing.JButton containerCancel;
    private javax.swing.JTextField containerMultiplicity;
    private javax.swing.JButton containerOK;
    private javax.swing.JTextField containerRoleName;
    private javax.swing.JCheckBox containerVisibleCheckbox;
    private javax.swing.JButton generalCancelButton;
    private javax.swing.JButton generalOkButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
